### ISSUE TITLE
Combine DataQueue and JsonMaker 

### ISSUE THREAD

**Issue by silviu-toderita** [supermileage/telemetry-firmware#27]
If you look in the lib/Telemetry folder, you will find some classes that the Telemetry team has built. 

The DataQueue class is what we "publish" new messages to instead of publishing to the cloud directly. The DataQueue object will store the message and attempt to publish it in the background (in a separate thread) when there is a cellular connection. We can keep "publishing" message to the DataQueue and it will store the newest messages up to its space limit. 

The JsonMaker class puts together a JSON message for us that contains various sensor data and the current time. The JSON message is generated using the format that the cloud side expects. 

From a quick glance at these 2 functions, it looks like they do a lot of similar things at the same time. Combine the functionality of both into the DataQueue class, to simplify our code base. 

Start by creating a new branch from the develop branch called develop_XXX (where XXX is the name of your feature). Compile the "proto" project and upload it to the Boron, and copy the output of the serial monitor so that you have a record of what the JSON output should look like. When you've finished combining the 2 classes, check to make sure your new JSON output is identical.

**Comment by cosparks** [comment]
JSONMaker eradicated.  Closing issue
