### ISSUE TITLE
Increase GPS Library Capability

### ISSUE THREAD

**Issue by silviu-toderita** [supermileage/telemetry-firmware#32]
Currently the GPS library (SensorGPS) can get an RMC sentence, which is used for the web map. It can also get speed from a portion of this sentence. We want to increase / improve the capability of this sensor library overall:

-In addition to RMS sentence, add the ability to get latitude and longitude atomically
-Get speed directly from GPS module instead of getting it from the RMC sentence
-Get some form of accuracy measurement 
-Get altitude
-Get acceleration (ideally from the GPS, otherwise we will have to calculate it in our code)

**Comment by cosparks** [comment]
Created new branch develop_gps for these changes
